-- Midwife Connect Rwanda
-- Run this once in Supabase SQL Editor.

create table if not exists public.course_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_slug text not null,
  completed boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (user_id, lesson_slug)
);

create table if not exists public.quiz_results (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  quiz_slug text not null,
  score integer not null check (score >= 0 and score <= 100),
  correct_answers integer not null default 0,
  total_questions integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.course_progress enable row level security;
alter table public.quiz_results enable row level security;

drop policy if exists "Users can read own course progress" on public.course_progress;
create policy "Users can read own course progress"
on public.course_progress for select
using (auth.uid() = user_id);

drop policy if exists "Users can insert own course progress" on public.course_progress;
create policy "Users can insert own course progress"
on public.course_progress for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can update own course progress" on public.course_progress;
create policy "Users can update own course progress"
on public.course_progress for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can read own quiz results" on public.quiz_results;
create policy "Users can read own quiz results"
on public.quiz_results for select
using (auth.uid() = user_id);

drop policy if exists "Users can insert own quiz results" on public.quiz_results;
create policy "Users can insert own quiz results"
on public.quiz_results for insert
with check (auth.uid() = user_id);

create index if not exists course_progress_user_idx on public.course_progress(user_id);
create index if not exists quiz_results_user_idx on public.quiz_results(user_id, created_at desc);
